import "../css/modern-normalize.css";
import "../css/style.css";
import "../css/components/header.css";
import "../css/components/hero.css";
import "../css/components/about.css";
import "../css/components/work.css";
import "../css/components/contact.css";
import "../css/components/footer.css";
import "../css/utils.css";
